name: "Zenodo Release Action"
description: "Release zenodo metadata so you don't have to give admin hook access"
inputs:
  archive:
    description: the path to the release archive
    required: true
  token:
    description: zenodo token
    required: true
  version:
    description: the release version
    required: true
  html_url:
    description: The HTML url to appear with the release (optional)
  zenodo_json:
    description: Path to zenodo.json to upload with metadata (must exist)
  doi:
    descripton: The DOI to create a new version from
  title:
    description: zenodo title (optional)
  description:
    description: zenodo description as plain text (optional)
  description_file:
    description: zenodo description from a file (optional)

outputs:
  badge:
    description: badge url
    value: ${{ steps.deploy.outputs.badge }}
  bucket:
    description: bucket url
    value: ${{ steps.deploy.outputs.bucket }}
  conceptbadge:
    description: concept badge url
    value: ${{ steps.deploy.outputs.conceptbadge }}
  conceptdoi:
    description: concept doi url
    value: ${{ steps.deploy.outputs.conceptdoi }}
  doi:
    description: doi url
    value: ${{ steps.deploy.outputs.doi }}
  latest:
    description: latest url
    value: ${{ steps.deploy.outputs.latest }}
  latest_html:
    description: latest html url
    value: ${{ steps.deploy.outputs.latest_html }}
  record:
    description: record url
    value: ${{ steps.deploy.outputs.record }}
  record_html:
    description: record html url
    value: ${{ steps.deploy.outputs.record_html }}

runs:
  using: "composite"
  steps:

    - name: Deploy Zenodo
      id: deploy
      env:
        zenodo_json: ${{ inputs.zenodo_json }}
        archive: ${{ inputs.archive }}
        version: ${{ inputs.version }}
        html_url: ${{ inputs.html_url }}
        ACTION_PATH: ${{ github.action_path }}
        ZENODO_TOKEN: ${{ inputs.token }}
        doi: ${{ inputs.doi }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        description_file: ${{ inputs.description_file }}
      run: |
        command=("python" "${{ github.action_path }}/scripts/deploy.py" "upload" "${archive}" "--version" "${version}")
        if [[ -n "${doi}" ]]; then
            command+=("--doi" "${doi}")
        fi
        if [[ -n "${title}" ]]; then
            command+=("--title" "${title}")
        fi
        if [[ -n "${description}" ]]; then
            command+=("--description" "${description}")
        elif [[ -n "${description_file}" ]]; then
            command+=("--description-file" "${description_file}")
        fi
        if [[ -n "${zenodo_json}" ]]; then
            command+=("--zenodo-json" "${zenodo_json}")
        fi
        if [[ -n "${html_url}" ]]; then
            command+=("--html-url" "${html_url}")
        fi
        printf "%s " "${command[@]}"
        "${command[@]}"

      shell: bash
